id: I286D1838
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:20.447123
last_modified: 2023-01-04 11:31:20.447132
source_metadata:
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
bases:
  77F9:
    title: Dhāraṇī of Goddess Parṇaśavarī
    base_file: 77F9.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
